; SVU already implements the Grizon airdrop module in SVUSniper.ini.
CommandSet RussianInfantrySVUSniperCommandSet
  7  = Command_RussiaCallinGrizonAirdrop
  15 = Command_AttackMove
  17 = Command_Guard
  18 = Command_Stop
End
